name: "Dependants Sync Action"
description: "Automates the synchronization of fields in GitHub Projects between parent issues and their dependents."

inputs:
  GITHUB_TOKEN:
    description: "GitHub token with project access."
    required: true
  PROJECT_URL:
    description: "The URL of your GitHub Project."
    required: true
  SYNC_FIELDS:
    description: "Comma-separated list of single select fields to synchronize."
    required: true
  TOP_PARENT_ISSUE_TYPE:
    description: "The Issue Type to use to determine the top parent issue (default: Initiative)."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
